const shopAPI = {
  status: "success",
  page: 1,
  limit: 50,
  total: 86,
  data: {
    cakes: [
      {
        id: 1,
        name: "کیک شکلاتی",
        category: "cake",
        price: 450000,
        discount: 0,
        stock: 12,
        description: "کیک شکلاتی نرم و خوشمزه با لایه‌های کرم شکلاتی",
        image_url: "/images/cakes/cake1.jpg",
        active: true,
      },
      {
        id: 2,
        name: "کیک وانیل کلاسیک",
        category: "cake",
        price: 400000,
        discount: 0,
        stock: 8,
        description: "کیک وانیلی کلاسیک با کرم وانیل و دکور جذاب",
        image_url: "/images/cakes/cake2.jpg",
        active: true,
      },
      {
        id: 3,
        name: "کیک ردولوت",
        category: "cake",
        price: 480000,
        discount: 0,
        stock: 5,
        description: "کیک ردولوت خوش رنگ با طعم کرم پنیر",
        image_url: "/images/cakes/cake3.jpg",
        active: true,
      },
      {
        id: 4,
        name: "کیک موزی",
        category: "cake",
        price: 420000,
        discount: 0,
        stock: 10,
        description: "کیک موزی خوشمزه با لایه کرم موز",
        image_url: "/images/cakes/cake4.jpg",
        active: true,
      },
      {
        id: 5,
        name: "کیک توت فرنگی",
        category: "cake",
        price: 470000,
        discount: 0,
        stock: 7,
        description: "کیک توت فرنگی تازه با کرم وانیل",
        image_url: "/images/cakes/cake5.jpg",
        active: true,
      },
      {
        id: 6,
        name: "کیک شکلاتی گرد",
        category: "cake",
        price: 460000,
        discount: 0,
        stock: 6,
        description: "کیک شکلاتی گرد با دکور شکلاتی",
        image_url: "/images/cakes/cake6.jpg",
        active: true,
      },
      {
        id: 7,
        name: "کیک کاراملی",
        category: "cake",
        price: 430000,
        discount: 0,
        stock: 9,
        description: "کیک کاراملی خوش طعم با لایه کارامل نرم",
        image_url: "/images/cakes/cake7.jpg",
        active: true,
      },
      {
        id: 8,
        name: "کیک شکلات و نارگیل",
        category: "cake",
        price: 480000,
        discount: 0,
        stock: 8,
        description: "کیک شکلاتی با رویه نارگیل رنده شده",
        image_url: "/images/cakes/cake8.jpg",
        active: true,
      },
      {
        id: 9,
        name: "کیک تولد ساده",
        category: "cake",
        price: 400000,
        discount: 0,
        stock: 15,
        description: "کیک تولد ساده با کرم وانیل",
        image_url: "/images/cakes/cake9.jpg",
        active: true,
      },
      {
        id: 10,
        name: "کیک قهوه‌ای",
        category: "cake",
        price: 450000,
        discount: 0,
        stock: 10,
        description: "کیک قهوه‌ای خوش طعم با کرم قهوه",
        image_url: "/images/cakes/cake10.jpg",
        active: true,
      },
      {
        id: 11,
        name: "کیک کاپوچینو",
        category: "cake",
        price: 460000,
        discount: 0,
        stock: 7,
        description: "کیک کاپوچینو با کرم شیر و قهوه",
        image_url: "/images/cakes/cake11.jpg",
        active: true,
      },
      {
        id: 12,
        name: "کیک نوتلا",
        category: "cake",
        price: 470000,
        discount: 0,
        stock: 6,
        description: "کیک شکلاتی با لایه نوتلا",
        image_url: "/images/cakes/cake12.jpg",
        active: true,
      },
      {
        id: 13,
        name: "کیک گرد شکلاتی با کرم",
        category: "cake",
        price: 480000,
        discount: 0,
        stock: 5,
        description: "کیک گرد شکلاتی با کرم شکلاتی لایه‌ای",
        image_url: "/images/cakes/cake13.jpg",
        active: true,
      },
      {
        id: 14,
        name: "کیک وانیل با میوه",
        category: "cake",
        price: 440000,
        discount: 0,
        stock: 9,
        description: "کیک وانیل با لایه میوه تازه و کرم وانیل",
        image_url: "/images/cakes/cake14.jpg",
        active: true,
      },
      {
        id: 15,
        name: "کیک نارگیلی",
        category: "cake",
        price: 450000,
        discount: 0,
        stock: 8,
        description: "کیک نارگیلی با کرم نرم",
        image_url: "/images/cakes/cake15.jpg",
        active: true,
      },
      {
        id: 16,
        name: "کیک شکلاتی سه طبقه",
        category: "cake",
        price: 500000,
        discount: 0,
        stock: 4,
        description: "کیک شکلاتی سه طبقه برای تولدهای بزرگ",
        image_url: "/images/cakes/cake16.jpg",
        active: true,
      },
      {
        id: 17,
        name: "کیک پرتقالی",
        category: "cake",
        price: 430000,
        discount: 0,
        stock: 10,
        description: "کیک پرتقالی تازه با کرم پرتقال",
        image_url: "/images/cakes/cake17.jpg",
        active: true,
      },
      {
        id: 18,
        name: "کیک یخچالی شکلاتی",
        category: "cake",
        price: 470000,
        discount: 0,
        stock: 5,
        description: "کیک یخچالی شکلاتی با طعم قوی",
        image_url: "/images/cakes/cake18.jpg",
        active: true,
      },
      {
        id: 19,
        name: "کیک کره‌ای",
        category: "cake",
        price: 420000,
        discount: 0,
        stock: 12,
        description: "کیک کره‌ای کلاسیک با کرم نرم",
        image_url: "/images/cakes/cake19.jpg",
        active: true,
      },
      {
        id: 20,
        name: "کیک توت فرنگی و شکلات",
        category: "cake",
        price: 480000,
        discount: 0,
        stock: 6,
        description: "کیک توت فرنگی با رویه شکلات",
        image_url: "/images/cakes/cake20.jpg",
        active: true,
      },
      {
        id: 21,
        name: "کیک سه رنگ",
        category: "cake",
        price: 500000,
        discount: 0,
        stock: 4,
        description: "کیک سه رنگ با لایه‌های شکلاتی و وانیلی",
        image_url: "/images/cakes/cake21.jpg",
        active: true,
      },
      {
        id: 22,
        name: "کیک شکلاتی با مغز فندق",
        category: "cake",
        price: 480000,
        discount: 0,
        stock: 5,
        description: "کیک شکلاتی با مغز فندق و کرم نرم",
        image_url: "/images/cakes/cake22.jpg",
        active: true,
      },
      {
        id: 23,
        name: "کیک وانیل و کاکائو",
        category: "cake",
        price: 450000,
        discount: 0,
        stock: 8,
        description: "کیک وانیل و کاکائو لایه‌ای با دکور جذاب",
        image_url: "/images/cakes/cake23.jpg",
        active: true,
      },
      {
        id: 24,
        name: "کیک موز و شکلات",
        category: "cake",
        price: 470000,
        discount: 0,
        stock: 7,
        description: "کیک موزی با لایه شکلاتی",
        image_url: "/images/cakes/cake24.jpg",
        active: true,
      },
      {
        id: 25,
        name: "کیک خامه‌ای",
        category: "cake",
        price: 430000,
        discount: 0,
        stock: 10,
        description: "کیک خامه‌ای نرم و تازه",
        image_url: "/images/cakes/cake25.jpg",
        active: true,
      },
      {
        id: 26,
        name: "کیک تولد گلدار",
        category: "cake",
        price: 480000,
        discount: 0,
        stock: 5,
        description: "کیک تولد با دکور گل شکلاتی",
        image_url: "/images/cakes/cake26.jpg",
        active: true,
      },
      {
        id: 27,
        name: "کیک با کرم وانیل",
        category: "cake",
        price: 450000,
        discount: 0,
        stock: 8,
        description: "کیک با کرم وانیل و طعم ملایم",
        image_url: "/images/cakes/cake27.jpg",
        active: true,
      },
      {
        id: 28,
        name: "کیک خامه‌ای و شکلاتی",
        category: "cake",
        price: 480000,
        discount: 0,
        stock: 6,
        description: "کیک خامه‌ای با رویه شکلاتی",
        image_url: "/images/cakes/cake28.jpg",
        active: true,
      },
      {
        id: 29,
        name: "کیک توت فرنگی با خامه",
        category: "cake",
        price: 470000,
        discount: 0,
        stock: 7,
        description: "کیک توت فرنگی با کرم تازه",
        image_url: "/images/cakes/cake29.jpg",
        active: true,
      },
      {
        id: 30,
        name: "کیک ویژه تولد",
        category: "cake",
        price: 500000,
        discount: 0,
        stock: 4,
        description: "کیک ویژه تولد با دکور زیبا",
        image_url: "/images/cakes/cake30.jpg",
        active: true,
      },
    ],
    desserts: [
      {
        id: 1,
        name: "پودینگ کارامل",
        category: "dessert",
        price: 120000,
        discount: 0,
        stock: 15,
        description: "پودینگ کارامل نرم و خوش طعم",
        image_url: "/images/desserts/des1.jpg",
        active: true,
      },
      {
        id: 2,
        name: "پاناکوتا وانیل",
        category: "dessert",
        price: 110000,
        discount: 0,
        stock: 12,
        description: "پاناکوتا وانیلی خوش طعم",
        image_url: "/images/desserts/des2.jpg",
        active: true,
      },
      {
        id: 3,
        name: "چیزکیک شکلاتی",
        category: "dessert",
        price: 140000,
        discount: 0,
        stock: 10,
        description: "چیزکیک شکلاتی با کرم نرم",
        image_url: "/images/desserts/des3.jpg",
        active: true,
      },
      {
        id: 4,
        name: "چیزکیک توت فرنگی",
        category: "dessert",
        price: 145000,
        discount: 0,
        stock: 8,
        description: "چیزکیک با لایه توت فرنگی تازه",
        image_url: "/images/desserts/des4.jpg",
        active: true,
      },
      {
        id: 5,
        name: "براونی شکلاتی",
        category: "dessert",
        price: 130000,
        discount: 0,
        stock: 14,
        description: "براونی نرم و خوشمزه",
        image_url: "/images/desserts/des5.jpg",
        active: true,
      },
      {
        id: 6,
        name: "دسر موز و کرم",
        category: "dessert",
        price: 120000,
        discount: 0,
        stock: 10,
        description: "دسر موزی با کرم نرم",
        image_url: "/images/desserts/des6.jpg",
        active: true,
      },
      {
        id: 7,
        name: "دسر کارامل و پودینگ",
        category: "dessert",
        price: 125000,
        discount: 0,
        stock: 12,
        description: "دسر کاراملی با لایه پودینگ",
        image_url: "/images/desserts/des7.jpg",
        active: true,
      },
      {
        id: 8,
        name: "موس شکلاتی",
        category: "dessert",
        price: 140000,
        discount: 0,
        stock: 15,
        description: "موس شکلاتی خوش طعم",
        image_url: "/images/desserts/des8.jpg",
        active: true,
      },
      {
        id: 9,
        name: "پودینگ وانیل",
        category: "dessert",
        price: 110000,
        discount: 0,
        stock: 18,
        description: "پودینگ وانیلی تازه",
        image_url: "/images/desserts/des9.jpg",
        active: true,
      },
      {
        id: 10,
        name: "دسر توت فرنگی",
        category: "dessert",
        price: 135000,
        discount: 0,
        stock: 10,
        description: "دسر توت فرنگی با کرم نرم",
        image_url: "/images/desserts/des10.jpg",
        active: true,
      },
      {
        id: 11,
        name: "کیک کوچک دسر",
        category: "dessert",
        price: 100000,
        discount: 0,
        stock: 20,
        description: "کیک کوچک دسر برای جشن‌ها",
        image_url: "/images/desserts/des11.jpg",
        active: true,
      },
      {
        id: 12,
        name: "موس توت",
        category: "dessert",
        price: 130000,
        discount: 0,
        stock: 12,
        description: "موس توت تازه",
        image_url: "/images/desserts/des12.jpg",
        active: true,
      },
      {
        id: 13,
        name: "دسر قهوه‌ای",
        category: "dessert",
        price: 125000,
        discount: 0,
        stock: 10,
        description: "دسر قهوه‌ای با کرم نرم",
        image_url: "/images/desserts/des13.jpg",
        active: true,
      },
      {
        id: 14,
        name: "دسر شکلات و کارامل",
        category: "dessert",
        price: 140000,
        discount: 0,
        stock: 8,
        description: "دسر شکلاتی با کارامل",
        image_url: "/images/desserts/des14.jpg",
        active: true,
      },
      {
        id: 15,
        name: "دسر وانیل و توت فرنگی",
        category: "dessert",
        price: 135000,
        discount: 0,
        stock: 12,
        description: "دسر وانیل با لایه توت فرنگی",
        image_url: "/images/desserts/des15.jpg",
        active: true,
      },
    ],
    pastries_with_cream: [
      {
        id: 1,
        name: "نان خامه‌ای کلاسیک",
        category: "pastry",
        price: 80000,
        discount: 0,
        stock: 20,
        description: "نان خامه‌ای تازه و خوشمزه با کرم نرم",
        image_url: "/images/pastries/pas1.jpg",
        active: true,
      },
      {
        id: 2,
        name: "شیرینی خامه‌ای توت فرنگی",
        category: "pastry",
        price: 85000,
        discount: 0,
        stock: 18,
        description: "شیرینی با کرم توت فرنگی",
        image_url: "/images/pastries/pas2.jpg",
        active: true,
      },
      {
        id: 3,
        name: "شیرینی کره‌ای و خامه‌ای",
        category: "pastry",
        price: 80000,
        discount: 0,
        stock: 15,
        description: "شیرینی کره‌ای با کرم نرم",
        image_url: "/images/pastries/pas3.jpg",
        active: true,
      },
      {
        id: 4,
        name: "شیرینی خامه‌ای گرد",
        category: "pastry",
        price: 85000,
        discount: 0,
        stock: 12,
        description: "شیرینی گرد با کرم نرم",
        image_url: "/images/pastries/pas4.jpg",
        active: true,
      },
      {
        id: 5,
        name: "شیرینی خامه‌ای شکلاتی",
        category: "pastry",
        price: 90000,
        discount: 0,
        stock: 10,
        description: "شیرینی شکلاتی با کرم خامه",
        image_url: "/images/pastries/pas5.jpg",
        active: true,
      },
      {
        id: 6,
        name: "شیرینی وانیلی و خامه‌ای",
        category: "pastry",
        price: 85000,
        discount: 0,
        stock: 15,
        description: "شیرینی وانیلی با کرم تازه",
        image_url: "/images/pastries/pas6.jpg",
        active: true,
      },
      {
        id: 7,
        name: "شیرینی موزی",
        category: "pastry",
        price: 80000,
        discount: 0,
        stock: 12,
        description: "شیرینی موزی با کرم تازه",
        image_url: "/images/pastries/pas7.jpg",
        active: true,
      },
      {
        id: 8,
        name: "شیرینی توت فرنگی",
        category: "pastry",
        price: 85000,
        discount: 0,
        stock: 14,
        description: "شیرینی توت فرنگی با کرم تازه",
        image_url: "/images/pastries/pas8.jpg",
        active: true,
      },
      {
        id: 9,
        name: "شیرینی خامه‌ای گرد کوچک",
        category: "pastry",
        price: 80000,
        discount: 0,
        stock: 10,
        description: "شیرینی گرد کوچک با کرم تازه",
        image_url: "/images/pastries/pas9.jpg",
        active: true,
      },
      {
        id: 10,
        name: "شیرینی کره‌ای با توت",
        category: "pastry",
        price: 85000,
        discount: 0,
        stock: 12,
        description: "شیرینی کره‌ای با کرم توت",
        image_url: "/images/pastries/pas10.jpg",
        active: true,
      },
    ],
    candles: [
      {
        id: 1,
        name: "شمع عدد 1",
        category: "candle",
        price: 15000,
        discount: 0,
        stock: 50,
        description: "شمع تولد عددی با رنگ جذاب",
        image_url: "/images/candles/can1.jpg",
        active: true,
      },
      {
        id: 2,
        name: "شمع عدد 2",
        category: "candle",
        price: 15000,
        discount: 0,
        stock: 50,
        description: "شمع تولد عددی با رنگ جذاب",
        image_url: "/images/candles/can2.jpg",
        active: true,
      },
      {
        id: 3,
        name: "شمع عدد 3",
        category: "candle",
        price: 15000,
        discount: 0,
        stock: 50,
        description: "شمع تولد عددی با رنگ جذاب",
        image_url: "/images/candles/can3.jpg",
        active: true,
      },
      {
        id: 4,
        name: "شمع عدد 4",
        category: "candle",
        price: 15000,
        discount: 0,
        stock: 50,
        description: "شمع تولد عددی با رنگ جذاب",
        image_url: "/images/candles/can4.jpg",
        active: true,
      },
      {
        id: 5,
        name: "شمع عدد 5",
        category: "candle",
        price: 15000,
        discount: 0,
        stock: 50,
        description: "شمع تولد عددی با رنگ جذاب",
        image_url: "/images/candles/can5.jpg",
        active: true,
      },
      {
        id: 6,
        name: "شمع عدد 6",
        category: "candle",
        price: 15000,
        discount: 0,
        stock: 50,
        description: "شمع تولد عددی با رنگ جذاب",
        image_url: "/images/candles/can6.jpg",
        active: true,
      },
      {
        id: 7,
        name: "شمع عدد 7",
        category: "candle",
        price: 15000,
        discount: 0,
        stock: 50,
        description: "شمع تولد عددی با رنگ جذاب",
        image_url: "/images/candles/can7.jpg",
        active: true,
      },
      {
        id: 8,
        name: "شمع عدد 8",
        category: "candle",
        price: 15000,
        discount: 0,
        stock: 50,
        description: "شمع تولد عددی با رنگ جذاب",
        image_url: "/images/candles/can8.jpg",
        active: true,
      },
      {
        id: 9,
        name: "شمع عدد 9",
        category: "candle",
        price: 15000,
        discount: 0,
        stock: 50,
        description: "شمع تولد عددی با رنگ جذاب",
        image_url: "/images/candles/can9.jpg",
        active: true,
      },
      {
        id: 10,
        name: "شمع عدد 10",
        category: "candle",
        price: 15000,
        discount: 0,
        stock: 50,
        description: "شمع تولد عددی با رنگ جذاب",
        image_url: "/images/candles/can10.jpg",
        active: true,
      },
    ],
    balloons: [
      {
        id: 1,
        name: "بادکنک لاتکس رنگی",
        category: "balloon",
        price: 5000,
        discount: 0,
        stock: 100,
        description: "بادکنک لاتکس رنگی مناسب تولد و جشن‌ها",
        image_url: "/images/balloons/bal1.jpg",
        active: true,
      },
      {
        id: 2,
        name: "بادکنک فویلی قلب",
        category: "balloon",
        price: 8000,
        discount: 0,
        stock: 50,
        description: "بادکنک فویلی شکل قلب",
        image_url: "/images/balloons/bal2.jpg",
        active: true,
      },
      {
        id: 3,
        name: "بادکنک فویلی ستاره",
        category: "balloon",
        price: 8000,
        discount: 0,
        stock: 50,
        description: "بادکنک فویلی شکل ستاره",
        image_url: "/images/balloons/bal3.jpg",
        active: true,
      },
      {
        id: 4,
        name: "بادکنک عددی",
        category: "balloon",
        price: 10000,
        discount: 0,
        stock: 50,
        description: "بادکنک عددی مناسب تولد",
        image_url: "/images/balloons/bal4.jpg",
        active: true,
      },
      {
        id: 5,
        name: "بادکنک لاتکس ساده",
        category: "balloon",
        price: 5000,
        discount: 0,
        stock: 100,
        description: "بادکنک لاتکس ساده برای تولد",
        image_url: "/images/balloons/bal5.jpg",
        active: true,
      },
    ],
    confetti: [
      {
        id: 1,
        name: "فشفشه رنگی",
        category: "confetti",
        price: 25000,
        discount: 0,
        stock: 30,
        description: "فشفشه رنگی برای جشن‌ها و تولدها",
        image_url: "/images/confetti/conf1.jpg",
        active: true,
      },
      {
        id: 2,
        name: "برف شادی",
        category: "confetti",
        price: 20000,
        discount: 0,
        stock: 20,
        description: "برف شادی برای جشن‌ها",
        image_url: "/images/confetti/conf2.jpg",
        active: true,
      },
    ],
    party_hats: [
      {
        id: 1,
        name: "کلاه تولد پسرانه 1",
        category: "party_hat",
        price: 15000,
        discount: 0,
        stock: 20,
        description: "کلاه تولد شاد و جذاب پسرانه",
        image_url: "/images/hats/boy1.jpg",
        active: true,
      },
      {
        id: 2,
        name: "کلاه تولد پسرانه 2",
        category: "party_hat",
        price: 15000,
        discount: 0,
        stock: 20,
        description: "کلاه تولد شاد و جذاب پسرانه",
        image_url: "/images/hats/boy2.jpg",
        active: true,
      },
      {
        id: 3,
        name: "کلاه تولد پسرانه 3",
        category: "party_hat",
        price: 15000,
        discount: 0,
        stock: 20,
        description: "کلاه تولد شاد و جذاب پسرانه",
        image_url: "/images/hats/boy3.jpg",
        active: true,
      },
      {
        id: 4,
        name: "کلاه تولد پسرانه 4",
        category: "party_hat",
        price: 15000,
        discount: 0,
        stock: 20,
        description: "کلاه تولد شاد و جذاب پسرانه",
        image_url: "/images/hats/boy4.jpg",
        active: true,
      },
      {
        id: 5,
        name: "کلاه تولد پسرانه 5",
        category: "party_hat",
        price: 15000,
        discount: 0,
        stock: 20,
        description: "کلاه تولد شاد و جذاب پسرانه",
        image_url: "/images/hats/boy5.jpg",
        active: true,
      },
      {
        id: 6,
        name: "کلاه تولد دخترانه 1",
        category: "party_hat",
        price: 15000,
        discount: 0,
        stock: 20,
        description: "کلاه تولد دخترانه شاد و جذاب",
        image_url: "/images/hats/girl1.jpg",
        active: true,
      },
      {
        id: 7,
        name: "کلاه تولد دخترانه 2",
        category: "party_hat",
        price: 15000,
        discount: 0,
        stock: 20,
        description: "کلاه تولد دخترانه شاد و جذاب",
        image_url: "/images/hats/girl2.jpg",
        active: true,
      },
      {
        id: 8,
        name: "کلاه تولد دخترانه 3",
        category: "party_hat",
        price: 15000,
        discount: 0,
        stock: 20,
        description: "کلاه تولد دخترانه شاد و جذاب",
        image_url: "/images/hats/girl3.jpg",
        active: true,
      },
      {
        id: 9,
        name: "کلاه تولد دخترانه 4",
        category: "party_hat",
        price: 15000,
        discount: 0,
        stock: 20,
        description: "کلاه تولد دخترانه شاد و جذاب",
        image_url: "/images/hats/girl4.jpg",
        active: true,
      },
      {
        id: 10,
        name: "کلاه تولد دخترانه 5",
        category: "party_hat",
        price: 15000,
        discount: 0,
        stock: 20,
        description: "کلاه تولد دخترانه شاد و جذاب",
        image_url: "/images/hats/girl5.jpg",
        active: true,
      },
      {
        id: 11,
        name: "کلاه تولد مردانه 1",
        category: "party_hat",
        price: 15000,
        discount: 0,
        stock: 20,
        description: "کلاه تولد مردانه شیک و جذاب",
        image_url: "/images/hats/man1.jpg",
        active: true,
      },
      {
        id: 12,
        name: "کلاه تولد مردانه 2",
        category: "party_hat",
        price: 15000,
        discount: 0,
        stock: 20,
        description: "کلاه تولد مردانه شیک و جذاب",
        image_url: "/images/hats/man2.jpg",
        active: true,
      },
      {
        id: 13,
        name: "کلاه تولد زنانه 1",
        category: "party_hat",
        price: 15000,
        discount: 0,
        stock: 20,
        description: "کلاه تولد زنانه شیک و جذاب",
        image_url: "/images/hats/woman1.jpg",
        active: true,
      },
      {
        id: 14,
        name: "کلاه تولد زنانه 2",
        category: "party_hat",
        price: 15000,
        discount: 0,
        stock: 20,
        description: "کلاه تولد زنانه شیک و جذاب",
        image_url: "/images/hats/woman2.jpg",
        active: true,
      },
    ],
  },
};
